"""initial migration

Revision ID: 7f2d69ca7cbf
Revises: 595dda87be70
Create Date: 2021-06-08 13:33:29.161654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f2d69ca7cbf'
down_revision = '595dda87be70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interests', schema=None) as batch_op:
        batch_op.drop_index('ix_interests_timestamp')

    op.drop_table('interests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interests', schema=None) as batch_op:
        batch_op.create_index('ix_interests_timestamp', ['timestamp'], unique=False)

    # ### end Alembic commands ###
